##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zr3xytosial5/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R source $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp media.css $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
 


